host_manager_19/host/urls.py
from django.conf.urls import url, include
from host import views

urlpatterns = [
    url(r'^host_list/$', views.host_list, name='host_list'),
    url(r'^host_add/$', views.host_change, name='host_add'),
    url(r'^host_edit/(\d+)$', views.host_change, name='host_edit'),
    url(r'^host_del/(\d+)$', views.host_del, name='host_del'),
    url(r'^login/$', views.login, name='login'),

]

host_manager_19/host_manager/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('host.urls', namespace='host')),

]

host_manager_19/host/models.py
from django.db import models
from rbac.models import RbacUser

class BusinessUnit(models.Model):
    name = models.CharField(max_length=32, verbose_name='业务线名称')
    
    def __str__(self):
        return self.name


class Host(models.Model):
    name = models.CharField(max_length=32, unique=True, verbose_name='主机名')
    ip = models.GenericIPAddressField(verbose_name='IP')
    bus_unit = models.ForeignKey('BusinessUnit', on_delete=models.CASCADE, verbose_name='业务线')


class User(RbacUser):
    username = models.CharField(max_length=32, verbose_name='用户名')
    password = models.CharField(max_length=32, verbose_name='密码')

host_manager_19/rbac/models.py
from django.db import models


class Menu(models.Model):
    """
    一级菜单
    """
    title = models.CharField(max_length=32)
    icon = models.CharField(max_length=64)
    weight = models.IntegerField(default=1)


class Permission(models.Model):
    """
    权限表
    有menu_id   ——》 权限是二级菜单
    没有menu_id   ——》 权限是普通的权限
    """
    url = models.CharField(max_length=64, verbose_name='权限')
    title = models.CharField(max_length=32, verbose_name='标题')
    name = models.CharField(max_length=32, verbose_name='URL别名', unique=True)
    menu = models.ForeignKey(Menu, blank=True, null=True)
    parent = models.ForeignKey('Permission', blank=True, null=True)
    
    def __str__(self):
        return self.title


class Role(models.Model):
    """
    角色表
    """
    name = models.CharField(max_length=32, verbose_name='名称')
    permissions = models.ManyToManyField('Permission', verbose_name='角色所拥有的权限', blank=True)
    
    def __str__(self):
        return self.name


class RbacUser(models.Model):
    """
    用户表
    """
    # username = models.CharField(max_length=32, verbose_name='用户名')
    # password = models.CharField(max_length=32, verbose_name='密码')
    roles = models.ManyToManyField(Role, verbose_name='用户所拥有的角色', blank=True)
    
    class Meta:
        abstract = True  # 数据库迁移的时候不生成表  作为基类 继承使用

host_manager_19/host/forms.py
from django import forms
from host import models


class BSForm(forms.ModelForm):
    
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class HostForm(BSForm):
    class Meta:
        model = models.Host
        fields = '__all__'

host_manager_19/host/views.py
from django.shortcuts import render, redirect, reverse
from host import models
from host.forms import HostForm
from utils.pagination import Pagination
from rbac.service.init_permission import init_permission


# Create your views here.
def host_list(request):
    all_hosts = models.Host.objects.all()
    page = Pagination(request.GET.get('page'), all_hosts.count(), request.GET.copy(), 1)
    return render(request, 'host_list.html', {
        'all_hosts': all_hosts[page.start:page.end],
        'page_html': page.page_html
    })


def host_change(request, pk=None):
    obj = models.Host.objects.filter(pk=pk).first()
    form_obj = HostForm(instance=obj)
    if request.method == 'POST':
        form_obj = HostForm(request.POST, instance=obj)
        if form_obj.is_valid():
            form_obj.save()
            
            next = request.GET.get('next')
            return redirect(next)
    
    return render(request, 'form.html', {'form_obj': form_obj})


def host_del(request, pk):
    models.Host.objects.filter(pk=pk).delete()
    return redirect('host:host_list')


def login(request):
    if request.method == 'POST':
        user = request.POST.get('username')
        pwd = request.POST.get('password')
        
        obj = models.User.objects.filter(username=user, password=pwd).first()
        if not obj:
            return render(request, 'login.html', {'error': '用户名或密码错误'})
        # 登录成功
        # 权限信息的初始化
        init_permission(request, obj)
        # 跳转到指定页面
        return redirect('host:host_list')
    return render(request, 'login.html')

host_manager_19/rbac/views.py
from django.shortcuts import render

# Create your views here.

host_manager_19/host/templates/host_list.html
{% extends 'layout.html' %}


{% block content %}
    {% load my_tags %}

    {% load rbac %}
    {% if request|has_permission:"host_add" %}
        <a class="btn btn-primary btn-sm" href="{% reverse_url request 'host:host_add' %}">添加</a>
    {% endif %}


    <table class="table-bordered table table-hover">
        <thead>
        <tr>
            <th>序号</th>
            <th>Id</th>
            <th>主机名</th>
            <th>IP</th>
            <th>业务线</th>
            {% if request|has_permission:"host_edit" or request|has_permission:"host_del" %}
                <th>操作</th>
            {% endif %}
        </tr>
        </thead>
        <tbody>
        {% for host in all_hosts %}

            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ host.pk }}</td>
                <td>{{ host.name }}</td>
                <td>{{ host.ip }}</td>
                <td>{{ host.bus_unit.name }}</td>
                {% if request|has_permission:"host_edit" or request|has_permission:"host_del" %}

                    <td>
                        {% if request|has_permission:"host_edit" %}

                            <a href="{% reverse_url request 'host:host_edit' host.pk %}"> <i
                                    class="fa fa-fw fa-edit"></i> </a>
                        {% endif %}

                        {% if request|has_permission:"host_del" %}

                            <a href="{% url 'host:host_del' host.pk %}"> <i class="fa fa-fw fa-trash-o"></i> </a>
                        {% endif %}
                    </td>
                {% endif %}
            </tr>
        {% endfor %}


        </tbody>
    </table>

    <nav aria-label="Page navigation">
        <ul class="pagination">
            {{ page_html }}
        </ul>
    </nav>


{% endblock %}