crmproject/crm/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from crm.crmviews import views_dep,views_user
urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^dep_list/', views_dep.dep_list,name='dep_list'),
    url(r'^dep_add/', views_dep.dep_add,name='dep_add'),
    url(r'^dep_edit/(\d+)/', views_dep.dep_edit,name='dep_edit'),
    url(r'^dep_del/(\d+)/', views_dep.dep_del,name='dep_del'),

    url(r'^user_list/', views_user.user_list, name='user_list'),
    url(r'^user_add/', views_user.user_add, name='user_add'),
    url(r'^user_edit/(\d+)/', views_user.user_edit, name='user_edit'),
    url(r'^user_del/(\d+)/', views_user.user_del, name='user_del'),
    url(r'^login/', views_user.login, name='login'),


]

crmproject/crmproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^crm/',include('crm.urls',namespace='crm')),
]

crmproject/crm/models.py
from django.db import models
from rabc.models import RbacUser

# Create your models here.
class Department(models.Model):
    name = models.CharField(max_length=64,verbose_name='部门名称')

    def __str__(self):
        return self.name


class User(RbacUser):
    name = models.CharField(max_length=32,verbose_name='用户名')
    pwd = models.CharField(max_length=32,verbose_name='密码')
    gender_choice =((1,'男'),(2,'女'))
    gender = models.IntegerField(choices=gender_choice,verbose_name='性别')
    dep = models.ForeignKey(to='Department',on_delete=models.CASCADE,verbose_name='部门')

    def __str__(self):
        return self.name

crmproject/rabc/models.py
from django.db import models

# Create your models here.
class Menu(models.Model):
    title = models.CharField(max_length=32)
    weight = models.IntegerField(default=1)
    icon = models.CharField(max_length=64)

    def __str__(self):
        return self.title


class Permission(models.Model):
    url = models.CharField(max_length=64, verbose_name='权限')
    title = models.CharField(max_length=32, verbose_name='标题')
    name = models.CharField(max_length=32, verbose_name='URL别名', unique=True)
    menu = models.ForeignKey(Menu, blank=True, null=True)
    parent = models.ForeignKey('Permission', blank=True, null=True)

    def __str__(self):
        return self.title

class Role(models.Model):
    name = models.CharField(max_length=64, verbose_name='名称')
    permissions = models.ManyToManyField('Permission',verbose_name='角色所拥有的权限',blank=True)

    def __str__(self):
        return self.name



class RbacUser(models.Model):
    """
    用户表
    """
    # username = models.CharField(max_length=32, verbose_name='用户名')
    # password = models.CharField(max_length=32, verbose_name='密码')
    roles = models.ManyToManyField(Role, verbose_name='用户所拥有的角色', blank=True)

    class Meta:
        abstract = True  # 数据库迁移的时候不生成表  作为基类 继承使用

crmproject/crm/forms.py
from django import forms
from crm import models
from django.core.exceptions import ValidationError

class Dep(forms.ModelForm):
    class Meta:
        model = models.Department
        fields = '__all__'

        widgets = {
            'name':forms.TextInput(attrs={
                'class':'form-control'
            })
        }

        error_messages ={
            'name':{
                'required':'不能为空'
            }
        }

    def clean_name(self):
        dname = self.cleaned_data.get('name')
        print(dname)
        print(dname)
        if models.Department.objects.filter(name=dname):
            raise ValidationError('该部门已存在')
        else:
            return dname



class UserForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = '__all__'

        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'pwd':forms.PasswordInput(attrs={'class':'form-control'}),
            # 'gender':forms.TextInput(attrs={'class':'form-control'}),
        #     'dep':forms.TextInput(attrs={'class':'form-control'}),
        }


    def clean_name(self):
        uname = self.cleaned_data.get('name')
        if models.User.objects.filter(name=uname):
            raise ValidationError('该用户已存在')
        else:
            return  uname

crmproject/rabc/views.py
from django.shortcuts import render

# Create your views here.

crmproject/templates/layout.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CRM管理系统</title>
    <link rel="shortcut icon" href="{% static 'imgs/luffy-study-logo.png' %} ">
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.css' %} "/>
    <link rel="stylesheet" href="{% static 'plugins/font-awesome/css/font-awesome.css' %} "/>
    <link rel="stylesheet" href="{% static 'css/commons.css' %} "/>
    <link rel="stylesheet" href="{% static 'css/nav.css' %} "/>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <style>
        body {
            margin: 0;
        }

        .no-radius {
            border-radius: 0;
        }

        .no-margin {
            margin: 0;
        }

        .pg-body > .left-menu {
            background-color: #EAEDF1;
            position: absolute;
            left: 1px;
            top: 48px;
            bottom: 0;
            width: 220px;
            border: 1px solid #EAEDF1;
            overflow: auto;
        }

        .pg-body > .right-body {
            position: absolute;
            left: 225px;
            right: 0;
            top: 48px;
            bottom: 0;
            overflow: scroll;
            border: 1px solid #ddd;
            border-top: 0;
            font-size: 13px;
            min-width: 755px;
        }

        .navbar-right {
            float: right !important;
            margin-right: -15px;
        }

        .luffy-container {
            padding: 15px;
        }

        .left-menu .menu-body .static-menu {

        }

        .left-menu .menu-body .static-menu .icon-wrap {
            width: 20px;
            display: inline-block;
            text-align: center;
        }

        .left-menu .menu-body .static-menu a {
            text-decoration: none;
            padding: 8px 15px;
            border-bottom: 1px solid #ccc;
            color: #333;
            display: block;
            background: #efefef;
            background: -webkit-gradient(linear, left bottom, left top, color-stop(0, #efefef), color-stop(1, #fafafa));
            background: -ms-linear-gradient(bottom, #efefef, #fafafa);
            background: -o-linear-gradient(bottom, #efefef, #fafafa);
            filter: progid:dximagetransform.microsoft.gradient(startColorStr='#e3e3e3', EndColorStr='#ffffff');
            -ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorStr='#fafafa',EndColorStr='#efefef')";
            box-shadow: inset 0 1px 1px white;
        }

        .left-menu .menu-body .static-menu a:hover {
            color: #2F72AB;
            border-left: 2px solid #2F72AB;
        }

        .left-menu .menu-body .static-menu a.active {
            color: #2F72AB;
            border-left: 2px solid #2F72AB;
        }
    </style>
    {% block css %} {% endblock %}
</head>
<body>

<div class="pg-header">
    <div class="nav">
        <div class="logo-area left">
            <a href="#">
                <img class="logo" src="{% static 'imgs/logo.svg' %}">
                <span style="font-size: 18px;">CRM管理系统 </span>
            </a>
        </div>

        <div class="left-menu left">
            <a class="menu-item" href="{% url 'crm:dep_list' %}">部门管理</a>
            <a class="menu-item" href="{%  url 'crm:user_list' %}">用户信息</a>
            <div class="menu-item">
                <span>使用说明</span>
                <i class="fa fa-caret-down" aria-hidden="true"></i>
                <div class="more-info">
                    <a href="#" class="more-item">管他什么菜单</a>
                    <a href="#" class="more-item">实在是编不了</a>
                </div>
            </div>
        </div>

        <div class="right-menu right clearfix">

            <div class="user-info right">
                <a href="#" class="avatar">
                    <img class="img-circle" src="{% static 'imgs/default.png' %}">
                </a>

                <div class="more-info">
                    <a href="#" class="more-item">个人信息</a>
                    <a href="#" class="more-item">注销</a>
                </div>
            </div>

            <a class="user-menu right">
                消息
                <i class="fa fa-commenting-o" aria-hidden="true"></i>
                <span class="badge bg-success">2</span>
            </a>

            <a class="user-menu right">
                通知
                <i class="fa fa-envelope-o" aria-hidden="true"></i>
                <span class="badge bg-success">2</span>
            </a>

            <a class="user-menu right">
                任务
                <i class="fa fa-bell-o" aria-hidden="true"></i>
                <span class="badge bg-danger">4</span>
            </a>
        </div>

    </div>
</div>
<div class="pg-body">
    <div class="left-menu">
        <div class="menu-body">
            <div class="static-menu">
                <a href="{% url 'crm:dep_list' %}"><span class="icon-wrap"><i class="fa fa-map-o" aria-hidden="true"></i></span>
                    部门管理</a>
                <a href="{% url 'crm:user_list' %}"><span class="icon-wrap"><i class="fa fa-map-o" aria-hidden="true"></i></span> 用户管理</a>
            </div>
        </div>
    </div>
    <div class="right-body">
        <div>
            <ol class="breadcrumb no-radius no-margin" style="border-bottom: 1px solid #ddd;">

                <li><a href="#">首页</a></li>
                <li class="active">客户管理</li>

            </ol>
        </div>
        {% block content %} {% endblock %}
    </div>
</div>


<script src="{% static 'js/jquery-3.3.1.min.js' %} "></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.js' %} "></script>
{% block js %} {% endblock %}
</body>
</html>

crmproject/templates/login.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta http-equiv="content-Type" charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
</head>
<body>

<form action="" method="post">
    {% csrf_token %}

    <p>
        用户名: <input type="text" name="username">
    </p>

    <p>
        密码： <input type="text" name="password">
    </p>
    <p>{{ error }}</p>
    <button>登录</button>
</form>


</body>
</html>